# Site settings
email: ryan_osterman@med.unc.edu
baseurl: "/"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: ryanosterman10's Portfolio
description: "A portfolio for ryanosterman10"
url: "https://ryanosterman10.github.io"
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
